# Use root/example as user/password credentials
version: '3.1'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: srvmosquitto
    restart : always
    volumes:
      - /home/wanderson/dvolumes/mosquitto/config:/mosquitto/config
      - /home/wanderson/dvolumes/mosquitto/data:/mosquitto/data
      - /home/wanderson/dvolumes/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883 #mqtt
      - 9001:9001 #websoquet
    networks:
      - net-dist

networks: 
  net-dist:
    driver: bridge